educations/urls.py
from django.urls import re_path, path
from educations import views
app_name = 'educations'
urlpatterns = [
	path('detail/<pk>/', views.education, name='education_n'),
    path('', views.education_list, name='educationlist_n'),
	path('create_eduorder/<pk>/', views.EduorderCreateView.as_view(), name='create_eduorder_n'),
	# path('create_eduorder/<int:education_id>/', views.EduorderCreateView.as_view(), name='create_eduorder_n'),

]

hall/urls.py
from . import views
from django.urls import path


app_name = 'hall'

urlpatterns = [
    path('', views.hall, name='hall_n'),
]

likwid_club/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from filebrowser.sites import site
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ref/', include('referals.urls')),
    path('posts/', include('modposting.urls')),
    path('product/', include('products.urls')),
    path('events/', include('events.urls')),
    path('educations/', include('educations.urls')),
    path('investions/', include('investions.urls')),
    path('basket_adding/', include('orders.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('checkout/', include('checkout.urls')),
    path('hall/', include('hall.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contacts/', include('contacts.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educations/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from tinymce import HTMLField
from accounts.models import Profile
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save


class EducationCategory(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Категория курсов'
		verbose_name_plural = 'Категории курсов'


class EducationFormat(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Формат курсов'
		verbose_name_plural = 'Форматы курсов'


class Education(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	image = models.ImageField(upload_to='educations_images/', null=True, default=None)
	price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
	category = models.ForeignKey(EducationCategory, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
	format = models.ForeignKey(EducationFormat, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
	duration = models.IntegerField(default=0)
	invites = models.IntegerField(default=0)
	description = models.TextField(max_length=256,blank=True, null=True, default=None)
	# content = HTMLField('Content', blank=True, null=True, default=None)
	is_disabled = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)
	publicated = models.DateTimeField(default=timezone.now, auto_now=False)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Курс'
		verbose_name_plural = 'Курсы'


class StatusEducationOrder(models.Model):
    status_name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.status_name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class EducationOrder(models.Model):
    customer_name = models.CharField("имя", max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField("электронная почта", max_length=64, blank=True, null=True, default=None)
    customer_phone = PhoneNumberField("телефон +7XXXXXXXX", max_length=24, blank=True, null=True, default=None)
    education = models.ForeignKey(Education, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    # referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=False, default=1)
    # referal_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, null=True)
    status = models.ForeignKey(StatusEducationOrder, on_delete=models.SET_DEFAULT, default=1)
    is_emailed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Заказ № %s %s" % (self.id, self.status.status_name)

    class Meta:
        verbose_name = 'Заказ курса'
        verbose_name_plural = 'Заказы курсов'

    def save(self, *args, **kwargs):
        super(EducationOrder, self).save(*args, **kwargs)


class EducationPlanPoint(models.Model):
    title = models.CharField(max_length=64, blank=True, null=True, default=None)
    education = models.ForeignKey(Education, on_delete=models.CASCADE, blank=True, null=True, default=None)
    content = HTMLField('Content', null=True, default=None)
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        verbose_name = 'Пункт плана курса'
        verbose_name_plural = 'Пункты плана курса'


class EducationResultPoint(models.Model):
    title = models.CharField(max_length=64, blank=True, null=True, default=None)
    education = models.ForeignKey(Education, on_delete=models.CASCADE, blank=True, null=True, default=None)
    content = HTMLField('Content', null=True, default=None)
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        verbose_name = 'Результат курса'
        verbose_name_plural = 'Результаты курса'


from .signals import send_mail_on_create
post_save.connect(send_mail_on_create,sender=EducationOrder,dispatch_uid="my_unique_identifier")

educations/forms.py
from django import forms
from .models import EducationOrder
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
# from django.forms import HiddenInput

class EducationOrderForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = EducationOrder
        fields = ['customer_name', 'customer_email','customer_phone']

educations/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from educations.models import Education
from django.utils import timezone
from .forms import EducationOrderForm
from .models import EducationOrder
from django.views import generic
from django.urls import reverse_lazy
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User


def education_list(request):
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    # educations = Education.objects.filter(is_active=True, publicated__lte=timezone.now()).order_by('-publicated')
    educations_live = Education.objects.filter(is_active=True, format__name='Очно', publicated__lte=timezone.now()).order_by('-publicated')
    educations_online = Education.objects.filter(is_active=True, format__name='Онлайн', publicated__lte=timezone.now()).order_by('-publicated')
    educations_forex = Education.objects.filter(is_active=True, category__name='Forex', publicated__lte=timezone.now()).order_by('-publicated')
    educations_future = Education.objects.filter(is_active=True, category__name='Срочный', publicated__lte=timezone.now()).order_by('-publicated')
    educations_fond = Education.objects.filter(is_active=True, category__name='Фондовый', publicated__lte=timezone.now()).order_by('-publicated')

    return render(request, 'educations/educations.html', locals())

def education(request, pk):
    # education = Education.objects.get(id=pk)
    education = get_object_or_404(Education, id=pk)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    return render(request, 'educations/education.html', locals())


class EduorderCreateView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
	# model = EducationOrder
    template_name = 'educations/create_eduorder.html'
    form_class = EducationOrderForm
    success_message = 'Ваша заявка принята, вскоре мы вам перезвоним.'
    # success_url = reverse_lazy('educations:education_n')
    def get_success_url(self):
        educations_pk=self.kwargs['pk']
        return reverse_lazy('educations:education_n', kwargs={'pk': educations_pk})

    def form_valid(self, form):
        if 'referer' in self.request.session:
            referer_id = self.request.session['referer']
            user = User.objects.get(pk=referer_id)
            # form.instance.referal = user.profile
            form.instance.referal = user.profile
        education = get_object_or_404(Education,pk=self.kwargs['pk'])
        form.instance.education = education
        # f=form.cleaned_data
        # # for k, v in form.cleaned_data.items():
        #     # print(k, '=', v)
        # # print(f.items())
        # print(f.get('customer_phone'))
        # print(education.name)
        # for key, value in f:
        #     print("%s = %s" % (key, value))
                # form.save()

        # if form.instance.is_emailed == False:
        #                 context = {
        #                 'order_name': form.instance.customer_name,
        #                 'order_number': instance.pk,
        #                 'order_edu': form.instance.education,
        #                 'contact_phone': form.instance.customer_phone,
        #                 }
        #             subject = 'Заказ курса № edu-%s' % instance.pk
        #             print(subject)
        #             html_message = render_to_string('includes/mail_template.html', context)
        #             plain_message = strip_tags(html_message)
        #             from_email = 'info@likwid.club'
        #             to = 'edu_orders@likwid.club'
        #
        #             if subject and html_message and from_email:
        #                 try:
        #                     if send_mail(subject, html_message, from_email, [to]):
        #                         EducationOrder.objects.filter(pk=instance.pk).update(is_emailed=True)
        #
        #                        # education_order = get_object_or_404(EducationOrder, id=instance.id)
        #                        # education_order.update(is_emailed=True)
        #                 except BadHeaderError:
        #                     print('Invalid header found in email')
        #                     return HttpResponse('Invalid header found.')
        #
        #                 # education_order.is_emailed = True
        #                 return HttpResponse('sended')
        #             else:
        #     	        print('Make sure all fields are entered and valid.')
        #     	        # to get proper validation errors.
        #     			# print('wring_any_field')
        #     	        # return HttpResponse('Make sure all fields are entered and valid.')
        #     if send_email(f, f):
        #
        #         print('done mail')
        #         form.instance.is_emailed = True
            # if send_email(form.cleaned_data):
        # form.instance.is_emailed = True
        # form.instance.is_emailed = True
        # form.save()
        return super(EduorderCreateView, self).form_valid(form)

templates/educations/create_eduorder.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <p class="modal-title">Оставьте Ваши контакты и мы вам перезвоним!</p>
    <button type="button" class="close btn-dark" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="form-row">
          <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
              {% for error in form.non_field_errors %}
              {{ error }}
              {% endfor %}
          </div>

          {% for field in form %}
          <div class="col-md-12">
              <label class="d-none invisible" for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% render_field field class="form-control my-1" placeholder=field.label %}
              <div class="{% if field.errors %} invalid{% endif %}">
                  {% for error in field.errors %}
                  <p class="help-block text-warning">{{ error }}</p>
                  {% endfor %}
              </div>
          </div>
          {% endfor %}
      </div>
  </div>

  <div class="modal-footer justify-content-center">
    <button type="button" class="submit-btn btn btn-dark">Заказать обучение!</button>
  </div>

</form>

templates/educations/education.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}

<section class="container-fluid">
    <div class="row flex-column flex-md-row justify-content-center pt-md-5">
        <div class="col-12 col-sm-4 col-md-2 py-4 px-5 px-md-0 py-md-0 align-top">
            <a id="back-link" class="text-nowrap text-muted" href="{% url 'educations:educationlist_n' %}"><i class="fas fa-chevron-left text-muted pr-2"></i>Вернуться назад</a>
        </div>
        <div class="col-12 col-md-5">
            <h3 class="text-center m-0 text-muted">{{ education.category }} рынок</h3>
            <h3 class="text-center m-0">{{ education.name }}</h3>
        </div>
        <div class="col-12 col-md-2">

        </div>
    </div>
    <div class="row justify-content-center pt-md-5">
        <div class="col-12 col-md-7 col-lg-8 col-xl-5 px-5 pt-5 pb-3 p-md-0 position-relative img-container">
                <img class="img-fl" src="{{ education.image.url }}" alt="Card image cap">
            <div class="in-event-date px-3 py-1">
                {{ education.format }}
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 py-0 px-5 py-md-5 text-left">

            <p class="py-1"> {{ education.description|truncatechars_html:500 }}</p>
            <table class="py-1">
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Длительность - {{ education.duration }} часов</td>
                </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Стоимость - {{ education.price }} руб</td>
               </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Доступно мест - {{ education.invites }}</td>
               </tr>
            </table>
            <div class="row mx-auto justify-content-left flex-xl-nowrap pt-3">
            <a class="btn btn-outline-light btn-lg text-nowrap btn-pink my-1" href="#" role="button">Начать обучение</a>
            </div>
        </div>
    </div>
</section>

<section>
    <h3 class="p-5 m-0 text-center">План занятий</h3>
</section>

<div class="container-fluid about-main">
    <div class="row flex-column align-content-center justify-content-center">
        {% for item in education.educationplanpoint_set.all %}
        <div class="col-12 col-md-9 py-5 px-5 px-md-0">
            <div class="col">
                <div class="row flex-column flex-md-row mb-4">
                    <div class="circle-number text-center pt-1 mr-3">{{ item.order }}</div><h3 class="p-0 m-0">{{ item.title }}</h3>
                </div>
            </div>
            <div class="col">
                {{ item.content | safe }}
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

templates/educations/educations.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}


<section class="container-fluid mb-5">
    <div class="row">
        <h3 class=" col-12 pt-5 pb-4 my-0 text-center">Обучение</h3>
        <div class="col-12">
            <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-edu-live-tab" data-toggle="pill" href="#pills-edu-live" role="tab" aria-controls="pills-edu-live" aria-selected="true">Очно</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-edu-online-tab" data-toggle="pill" href="#pills-edu-online" role="tab" aria-controls="pills-edu-online" aria-selected="false">Онлайн</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-edu-forex-tab" data-toggle="pill" href="#pills-edu-forex" role="tab" aria-controls="pills-edu-forex" aria-selected="false">Forex</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-edu-fond-tab" data-toggle="pill" href="#pills-edu-fond" role="tab" aria-controls="pills-edu-fond" aria-selected="false">Фондовый</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-edu-future-tab" data-toggle="pill" href="#pills-edu-future" role="tab" aria-controls="pills-edu-future" aria-selected="false">Срочный</a>
                </li>
            </ul>
        </div>

        <div class="tab-content col-12 p-0" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-edu-live" role="tabpanel" aria-labelledby="pills-edu-live-tab">
                {% for education_item in educations_live %}
                {% include 'educations/educations_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-edu-forex" role="tabpanel" aria-labelledby="pills-edu-forex-tab">
                {% for education_item in educations_forex %}
                {% include 'educations/educations_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-edu-online" role="tabpanel" aria-labelledby="pills-edu-online-tab">
                {% for education_item in educations_online %}
                {% include 'educations/educations_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-edu-fond" role="tabpanel" aria-labelledby="pills-edu-fond-tab">
                {% for education_item in educations_fond %}
                {% include 'educations/educations_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-edu-future" role="tabpanel" aria-labelledby="pills-edu-future-tab">
                {% for education_item in educations_future %}
                {% include 'educations/educations_cards.html' %}
                {% endfor %}
          </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/educations/educations_cards.html
{% block educations_cards %}


<section class="container-fluid">
    <div class="row justify-content-center pt-md-5">
        <div class="col-12 col-md-7 col-lg-8 col-xl-5 px-5 pt-5 pb-3 p-md-0 position-relative img-container">
                <img class="img-fl" src="{{ education_item.image.url }}" alt="Card image cap">
            <div class="in-event-date px-3 py-1">
                {{ education_item.format }}
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 py-0 px-5 py-md-5 text-left">
            <h3>{{ education_item.category }}</h3>
            <h5>{{ education_item.name }}</h5>
            <p class="py-1"> {{ education_item.description|truncatechars_html:500 }}</p>
            <table class="py-1">
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Длительность - {{ education_item.duration }} часов</td>
                </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Стоимость - {{ education_item.price }} рублей</td>
               </tr>
            </table>
            <div class="row mx-auto justify-content-left flex-xl-nowrap pt-3">
            <a class="btn btn-outline-light btn-lg text-nowrap flex-grow-1 btn-pink my-1" href="#" role="button">Начать обучение</a>
            <a type=""  href="{% url 'educations:education_n' education_item.id %}" class="btn btn-form  text-nowrap flex-grow-1 ml-0 ml-sm-3 ml-md-0 ml-xl-3 my-1">План занятий</a>
            </div>
        </div>
    </div>
</section>


{% endblock educations_cards %}

<!-- <div onclick="location.href='http://google.com';"></div> -->