hall/urls.py
from . import views
from django.urls import path


app_name = 'hall'

urlpatterns = [
    path('', views.hall, name='hall_n'),
]

investions/urls.py
from django.urls import re_path, path
from investions import views
app_name = 'investions'
urlpatterns = [
	path('<pk>/', views.investion, name='investion_n'),
    path('', views.investion_list, name='investionlist_n'),
	# path('create_eduorder/<pk>/', views.EduorderCreateView.as_view(), name='create_eduorder_n'),
]

likwid_club/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from filebrowser.sites import site
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ref/', include('referals.urls')),
    path('posts/', include('modposting.urls')),
    path('product/', include('products.urls')),
    path('events/', include('events.urls')),
    path('educations/', include('educations.urls')),
    path('investions/', include('investions.urls')),
    path('basket_adding/', include('orders.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('checkout/', include('checkout.urls')),
    path('hall/', include('hall.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contacts/', include('contacts.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investions/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from tinymce import HTMLField
from accounts.models import Profile
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save


class InvestionCategory(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Категория инвестиций'
		verbose_name_plural = 'Категории инвестиций'


class InvestionFormat(models.Model):
	name = models.CharField(max_length=32, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Формат инвестиций'
		verbose_name_plural = 'Форматы инвестиций'


class Investion(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	image = models.ImageField(upload_to='investions_images/', null=True, default=None)
	price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
	category = models.ForeignKey(InvestionCategory, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
	format = models.ForeignKey(InvestionFormat, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
	duration = models.IntegerField(default=0)
	invites = models.IntegerField(default=0)
	description = models.TextField(max_length=256,blank=True, null=True, default=None)
	# content = HTMLField('Content', blank=True, null=True, default=None)
	is_disabled = models.BooleanField(default=False)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)
	publicated = models.DateTimeField(default=timezone.now, auto_now=False)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Инвестиция'
		verbose_name_plural = 'Инвестиции'


class StatusInvestionOrder(models.Model):
    status_name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.status_name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class InvestionOrder(models.Model):
    customer_name = models.CharField("имя", max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField("электронная почта", max_length=64, blank=True, null=True, default=None)
    customer_phone = PhoneNumberField("телефон +7XXXXXXXX", max_length=24, blank=True, null=True, default=None)
    investion = models.ForeignKey(Investion, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    # referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=False, default=1)
    # referal_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, null=True)
    status = models.ForeignKey(StatusInvestionOrder, on_delete=models.SET_DEFAULT, default=1)
    is_emailed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Заказ № %s %s" % (self.id, self.status.status_name)

    class Meta:
        verbose_name = 'Заказ инвестиции'
        verbose_name_plural = 'Заказы инвестиций'

    def save(self, *args, **kwargs):
        super(InvestionOrder, self).save(*args, **kwargs)


class InvestionPlanPoint(models.Model):
    order = models.IntegerField(default=0)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    investion = models.ForeignKey(Investion, on_delete=models.CASCADE, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        verbose_name = 'Характеристика инвестиции'
        verbose_name_plural = 'Характеристики инвестиций'


class InvestionResultPoint(models.Model):
    order = models.IntegerField(default=0)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    investion = models.ForeignKey(Investion, on_delete=models.CASCADE, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        verbose_name = 'Преимущество инвестиции'
        verbose_name_plural = 'Преимущества инвестиций'


# from .signals import send_mail_on_create
# post_save.connect(send_mail_on_create,sender=InvestionOrder,dispatch_uid="my_unique_identifier")

investions/forms.py
from django import forms
from .models import InvestionOrder
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
# from django.forms import HiddenInput

class InvestionOrderForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = InvestionOrder
        fields = ['customer_name', 'customer_email','customer_phone']

investions/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from investions.models import Investion
from django.utils import timezone
from .forms import InvestionOrderForm
from .models import InvestionOrder
from django.views import generic
from django.urls import reverse_lazy
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User


def investion_list(request):
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    # investions = investion.objects.filter(is_active=True, publicated__lte=timezone.now()).order_by('-publicated')
    investions_big = Investion.objects.filter(is_active=True, format__name='>30%', publicated__lte=timezone.now()).order_by('-publicated')
    investions_medium = Investion.objects.filter(is_active=True, format__name='10-12%', publicated__lte=timezone.now()).order_by('-publicated')
    investions_small = Investion.objects.filter(is_active=True, format__name='10%', publicated__lte=timezone.now()).order_by('-publicated')
    return render(request, 'investions/investions.html', locals())

def investion(request, pk):
    # investion = investion.objects.get(id=pk)
    investion = get_object_or_404(Investion, id=pk)
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    return render(request, 'investions/investion.html', locals())


class InvorderCreateView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
	# model = investionOrder
    template_name = 'investions/create_eduorder.html'
    form_class = InvestionOrderForm
    success_message = 'Ваша заявка принята, вскоре мы вам перезвоним.'
    # success_url = reverse_lazy('investions:investion_n')
    def get_success_url(self):
        investions_pk=self.kwargs['pk']
        return reverse_lazy('investions:investion_n', kwargs={'pk': investions_pk})

    def form_valid(self, form):
        if 'referer' in self.request.session:
            referer_id = self.request.session['referer']
            user = User.objects.get(pk=referer_id)
            # form.instance.referal = user.profile
            form.instance.referal = user.profile
        investion = get_object_or_404(Investion,pk=self.kwargs['pk'])
        form.instance.investion = investion

        return super(EduorderCreateView, self).form_valid(form)

templates/investions/investion.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}

<section class="container-fluid">
    <div class="row flex-column flex-md-row justify-content-center pt-md-5">
        <div class="col-12 col-sm-4 col-md-2 py-4 px-5 px-md-0 py-md-0 align-top">
            <a id="back-link" class="text-nowrap text-muted" href="{% url 'investions:investionlist_n' %}"><i class="fas fa-chevron-left text-muted pr-2"></i>Вернуться назад</a>
        </div>
        <div class="col-12 col-md-5">
            <h3 class="text-center m-0 px-5">{{ investion.name }}</h3>
        </div>
        <div class="col-12 col-md-2">

        </div>
    </div>
    <div class="row justify-content-center pt-md-5">
        <div class="col-12 col-md-7 col-lg-8 col-xl-5 px-5 pt-5 pb-3 p-md-0 position-relative img-container">
                <img class="img-fl" src="{{ investion.image.url }}" alt="Card image cap">
            <div class="in-event-date px-3 py-1">
                {{ investion.format }}
            </div>
        </div>
        <div class="col-12 col-md-4 col-lg-4 py-0 px-5 py-md-5 text-left">

            <p class="py-1"> {{ investion.description|truncatechars_html:500 }}</p>
            <table class="py-1 d-none">
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Длительность - {{ investion.duration }} часов</td>
                </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Стоимость - {{ investion.price }} руб</td>
               </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Доступно мест - {{ investion.invites }}</td>
               </tr>
            </table>
            <div class="row mx-auto justify-content-left flex-xl-nowrap pt-3">
            <a class="btn btn-outline-light btn-lg text-nowrap btn-pink my-1" href="#" role="button">Приобрести</a>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid mt-5">
        <div class="row justify-content-end bg-likwid">
                <div class="col-12 col-lg-6 p-5 d-md-flex flex-wrap d-lg-block text-light">
                    <h4 class="mb-3 col-12 pl-0 pl-lg-2">Характеристики</h4>
                    {% for item in investion.investionplanpoint_set.all %}
                    <div class="col-12 col-md-4 col-lg-12 pl-0 pl-lg-2">
                            <div class="d-lg-flex">
                                <div class="mr-3">0{{ item.order }}</div>
                                <p class="text-light">{{ item.title }}</p>
                            </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="col-12 col-lg-5 p-5 d-md-flex flex-wrap d-lg-block bg-light">
                    <h4 class="mb-3 col-12 pl-0">Преимущества</h4>
                    {% for item in investion.investionresultpoint_set.all %}
                    <div class="col-12 col-md-4 col-lg-12 pl-0">
                            <div class="d-lg-flex">
                                <div class="text-muted mr-3">0{{ item.order }}</div>
                                <p class="">{{ item.title }}</p>
                            </div>
                    </div>
                    {% endfor %}
                    <a class="btn btn-outline-light btn-lg text-nowrap btn-pink my-1" href="#" role="button">Записаться</a>
                </div>
        </div>
    </div>
</section>



{% endblock content %}

templates/investions/investions.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}


<section class="container-fluid mb-5">
    <div class="row">
        <h3 class=" col-12 pt-5 pb-4 my-0 text-center">Инвестиции</h3>

        <div class="col-12">
            <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-inv-big-tab" data-toggle="pill" href="#pills-inv-big" role="tab" aria-controls="pills-inv-big" aria-selected="true">>30%</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-inv-medium-tab" data-toggle="pill" href="#pills-inv-medium" role="tab" aria-controls="pills-inv-medium" aria-selected="false">10-12%</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pills-inv-small-tab" data-toggle="pill" href="#pills-inv-small" role="tab" aria-controls="pills-inv-small" aria-selected="false">10%</a>
                </li>
            </ul>
        </div>

        <div class="tab-content col-12 p-0" id="pills-tabContent">
              <div class="tab-pane fade show active" id="pills-inv-big" role="tabpanel" aria-labelledby="pills-inv-big-tab">
                    {% for investion_item in investions_big %}
                    {% include 'investions/investions_cards.html' %}
                    {% endfor %}
              </div>
              <div class="tab-pane fade" id="pills-inv-small" role="tabpanel" aria-labelledby="pills-inv-small-tab">
                    {% for investion_item in investions_small %}
                    {% include 'investions/investions_cards.html' %}
                    {% endfor %}
              </div>
              <div class="tab-pane fade" id="pills-inv-medium" role="tabpanel" aria-labelledby="pills-inv-medium-tab">
                    {% for investion_item in investions_medium %}
                    {% include 'investions/investions_cards.html' %}
                    {% endfor %}
              </div>
        </div>
    </div>
</section>

{% endblock content %}