hall/urls.py
from . import views
from django.urls import path


app_name = 'hall'

urlpatterns = [
    path('', views.hall, name='hall_n'),
]

investions/urls.py
from django.urls import re_path, path
from investions import views
app_name = 'investions'
urlpatterns = [
	path('<pk>/', views.investion, name='investion_n'),
    path('', views.investion_list, name='investionlist_n'),
	# path('create_eduorder/<pk>/', views.EduorderCreateView.as_view(), name='create_eduorder_n'),
]

likwid_club/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from filebrowser.sites import site
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ref/', include('referals.urls')),
    path('posts/', include('modposting.urls')),
    path('product/', include('products.urls')),
    path('events/', include('events.urls')),
    path('educations/', include('educations.urls')),
    path('investions/', include('investions.urls')),
    path('basket_adding/', include('orders.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('checkout/', include('checkout.urls')),
    path('hall/', include('hall.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contacts/', include('contacts.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hall/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models.signals import post_save


class MemberPreference(models.Model):
    order = models.IntegerField("Порядок следования", default=0)
    title = models.CharField(max_length=128, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.title

    class Meta:
        verbose_name = 'Преференции'
        verbose_name_plural = 'Что дает членство клуба'


class Bill(models.Model):
    order = models.IntegerField("Порядок следования",default=0)
    broker_image = models.ImageField(upload_to='broker_images/', null=True, default=None)
    duration = models.TextField(max_length=128,blank=True, null=True, default=None)
    result = models.TextField(max_length=128,blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.broker_image

    class Meta:
        verbose_name = 'Брокер'
        verbose_name_plural = 'Брокеры'

#
# class StatusInvestionOrder(models.Model):
#     status_name = models.CharField(max_length=24, blank=True, null=True, default=None)
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True , auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False , auto_now=True)
#
#     def __str__(self):
#         return "%s" % self.status_name
#
#     class Meta:
#         verbose_name = 'Статус заказа'
#         verbose_name_plural = 'Статусы заказа'
#
#
# class InvestionOrder(models.Model):
#     customer_name = models.CharField("имя", max_length=64, blank=True, null=True, default=None)
#     customer_email = models.EmailField("электронная почта", max_length=64, blank=True, null=True, default=None)
#     customer_phone = PhoneNumberField("телефон +7XXXXXXXX", max_length=24, blank=True, null=True, default=None)
#     investion = models.ForeignKey(Investion, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
#     referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
#     # referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=False, default=1)
#     # referal_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, null=True)
#     status = models.ForeignKey(StatusInvestionOrder, on_delete=models.SET_DEFAULT, default=1)
#     is_emailed = models.BooleanField(default=False)
#     created = models.DateTimeField(auto_now_add=True, auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False, auto_now=True)
#
#     def __str__(self):
#         return "Заказ № %s %s" % (self.id, self.status.status_name)
#
#     class Meta:
#         verbose_name = 'Заказ инвестиции'
#         verbose_name_plural = 'Заказы инвестиций'
#
#     def save(self, *args, **kwargs):
#         super(InvestionOrder, self).save(*args, **kwargs)


# from .signals import send_mail_on_create
# post_save.connect(send_mail_on_create,sender=InvestionOrder,dispatch_uid="my_unique_identifier")

hall/views.py
from django.shortcuts import render
from .models import MemberPreference, Bill

# Create your views here.
def hall(request):
    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    # investions = investion.objects.filter(is_active=True, publicated__lte=timezone.now()).order_by('-publicated')
    preferences = MemberPreference.objects.filter(is_active=True).order_by('-order')
    broker_list = Bill.objects.filter(is_active=True).order_by('-order')

    return render(request, 'hall/hall.html', locals())

templates/hall/create_invorder.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <p class="modal-title">Оставьте Ваши контакты и мы вам перезвоним!</p>
    <button type="button" class="close btn-dark" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="form-row">
          <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
              {% for error in form.non_field_errors %}
              {{ error }}
              {% endfor %}
          </div>

          {% for field in form %}
          <div class="col-md-12">
              <label class="d-none invisible" for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% render_field field class="form-control my-1" placeholder=field.label %}
              <div class="{% if field.errors %} invalid{% endif %}">
                  {% for error in field.errors %}
                  <p class="help-block text-warning">{{ error }}</p>
                  {% endfor %}
              </div>
          </div>
          {% endfor %}
      </div>
  </div>

  <div class="modal-footer justify-content-center">
    <button type="button" class="submit-btn btn btn-dark">Заказать обучение!</button>
  </div>

</form>

templates/hall/hall.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}

<section>
    <h3 class="pt-5 my-0 text-center">Закрытый клуб LIKWID</h3>
</section>

<section class="container-fluid">
    <div class="row justify-content-center pt-md-5 pb-md-5">
        <div class="col-12 col-md-7 col-lg-5 col-xl-5 pb-0 pt-5 px-5 p-md-0 position-relative img-container">
            <img class="img-fl" src="{% static 'img/img36.png' %}" alt="Second slide">
        </div>
        <div class="col-12 col-md-5 col-lg-4 px-5 pb-5 pt-4 py-sm-5 pr-lg-0">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            <a class="btn btn-outline-light btn-lg text-nowrap btn-pink" href="#" role="button">Вступить</a>
        </div>
    </div>
</section>

<section class="container-fluid px-0 bg-light">
    <div class="row col-12 col-md-9 mx-auto px-0">
        <div class="col-12 p-5 pl-md-0">
            <img class="img-fluid d-md-inline mr-3 mb-3" src="{% static 'img/star.png' %}" alt="">
            <h4 class="d-md-inline m-0">Что дает членство клуба?</h4>
        </div>
            {% for item in preferences %}
            <div class="col-12 col-md-4 pb-5 pt-0 pl-5 pl-md-0 pr-5">
                <div class="">
                    <div class="mr-3 text-muted">01 0{{ item.order }}</div>
                    <p class="text-dark">{{ item.title }}</p>
                </div>
            </div>
            {% endfor %}
</section>


<section>
    <div class="container-fluid">
        <div class="row justify-content-end bg-likwid">
                <div class="col-12 col-lg-6 px-5 py-5 pr-md-3 d-md-flex flex-wrap d-lg-block text-light">
                    <h4 class="mb-3 col-12 pl-0 ">Открыть счет</h4>
                    <p class="text-light col-md-9 px-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    {% for item in broker_list %}
                    <div class="container-fluid p-0">
                        <div class="row col-12 justify-content-between align-items-center border-bottom border-light d-block-inline px-0 my-2 mx-0 pb-3">
                            <div class="col-3 p-0">
                                <img class="img-fluid" src="{{ item.broker_image.url }}" alt="">
                            </div>
                            <div class="col-5">
                                <p class="text-light m-0 small-text">{{ item.duration }}</p>
                                <p class="text-light m-0 small-text">{{ item.result }}</p>
                            </div>
                                <a class="btn btn-outline-light btn-lg text-nowrap btn-pink small-text col-4 p-2 " href="#" role="button">Открыть счет</a>
                        </div>
                    </div>
                          {% endfor %}
                </div>
                <div class="col-12 col-lg-5 p-5 d-md-flex flex-wrap bg-light">
                    <h4 class="mb-3 col-12 pl-0">Подписка на членство клуба</h4>
                    <div class="col-12 col-md-9 pl-0">
                                <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                                <p class="">Lorem ipsum dolor sit amet, consectetur adipisicing elit.Lorem ipsum dolor sit amet, consectetur adipisicing elitLorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                    <div class="col-6 p-0">
                        <a class="btn btn-outline-light btn-lg text-nowrap btn-pink my-1" href="#" role="button">Вступить в клуб</a>
                    </div>
                </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/hall/investions_cards.html
{% block investions_cards %}


<section class="container-fluid">
    <div class="row justify-content-center pt-md-5">
        <div class="col-12 col-md-7 col-lg-8 col-xl-5 px-5 pt-5 pb-3 p-md-0 position-relative img-container">
                <img class="img-fl" src="{{ investion_item.image.url }}" alt="Card image cap">
            <div class="in-event-date px-3 py-1">
                {{ investion_item.format }}
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 py-0 px-5 py-md-5 text-left">
            <h5>{{ investion_item.name }}</h5>
            <p class="py-1"> {{ investion_item.description|truncatechars_html:500 }}</p>
            <table class="py-1 d-none">
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Длительность - {{ investion_item.duration }} часов</td>
                </tr>
                <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2 text-nowrap">Стоимость - {{ investion_item.price }} рублей</td>
               </tr>
            </table>
            <div class="row mx-auto justify-content-left flex-xl-nowrap pt-3">
            <a class="btn btn-outline-light btn-lg text-nowrap btn-pink" href="{% url 'investions:investion_n' investion_item.id %}" role="button">Подробнее</a>
            </div>

        </div>
    </div>
</section>


{% endblock investions_cards %}

<!-- <div onclick="location.href='http://google.com';"></div> -->