events/urls.py
from django.urls import re_path, path
from events import views
app_name = 'events'

urlpatterns = [
    path('', views.events_list, name='eventslist_n'),
    path('<pk>/', views.event, name='event_n'),
    path('join_event/<pk>/', views.EventJoinView.as_view(), name='join_event_n'),
]

hall/urls.py
from . import views
from django.urls import path


app_name = 'hall'

urlpatterns = [
    path('', views.hall, name='hall_n'),
]

likwid_club/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from filebrowser.sites import site
from django.conf import settings
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ref/', include('referals.urls')),
    path('posts/', include('modposting.urls')),
    path('product/', include('products.urls')),
    path('events/', include('events.urls')),
    path('educations/', include('educations.urls')),
    path('investions/', include('investions.urls')),
    path('basket_adding/', include('orders.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('checkout/', include('checkout.urls')),
    path('hall/', include('hall.urls')),
    path('aboutus/', include('aboutus.urls')),
    path('contacts/', include('contacts.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.utils import timezone
from tinymce import HTMLField
from accounts.models import Profile
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save


class EventFormat(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True, default=None)
	is_active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True , auto_now=False)
	updated = models.DateTimeField(auto_now_add=False , auto_now=True)

	def __str__(self):
		return "%s" % self.name

	class Meta:
		verbose_name = 'Формат мероприятия'
		verbose_name_plural = 'Форматы мероприятия'


class EventCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория мероприятия'
        verbose_name_plural = 'Категории мероприятий'


class Event(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    # image = models.ImageField(upload_to='event_images/', null=True, default=None)
    category = models.ForeignKey(EventCategory, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
    format = models.ForeignKey(EventFormat, on_delete=models.SET_DEFAULT, max_length=64, blank=True, null=True, default=None)
    description = models.TextField(max_length=256,blank=True, null=True, default=None)
    # content = HTMLField('Content', null=True, default=None)
    is_active = models.BooleanField(default=True)
    publicated = models.DateTimeField(default=timezone.now, auto_now=False)
    event_date = models.DateTimeField(default=timezone.now, blank=False, auto_now=False)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'


class StatusEventJoiner(models.Model):
    status_name = models.CharField(max_length=24, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.status_name

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class EventJoiner(models.Model):
    customer_name = models.CharField("имя", max_length=64, blank=True, null=True, default=None)
    customer_email = models.EmailField("электронная почта", max_length=64, blank=True, null=True, default=None)
    customer_phone = PhoneNumberField("телефон +7XXXXXXXX", max_length=24, blank=True, null=True, default=None)
    event = models.ForeignKey(Event, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    # referal = models.ForeignKey(Profile, on_delete=models.SET_DEFAULT, blank=False, default=1)
    # referal_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, null=True)
    status = models.ForeignKey(StatusEventJoiner, on_delete=models.SET_DEFAULT, default=1)
    is_emailed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "Заказ № %s %s" % (self.id, self.status.status_name)

    class Meta:
        verbose_name = 'Подписавшийся на мероприятия'
        verbose_name_plural = 'Подписавшиеся на мероприятия'


class EventImage(models.Model):
    event = models.ForeignKey(Event, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None)
    image = models.ImageField(upload_to='product_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True , auto_now=False)
    updated = models.DateTimeField(auto_now_add=False , auto_now=True)

    def __str__(self):
        return "%s" % self.image

    class Meta:
        verbose_name = 'Фотография мероприятия'
        verbose_name_plural = 'Фотографии мероприятий'


# class EventPlanPoint(models.Model):
#     title = models.CharField(max_length=64, blank=True, null=True, default=None)
#     event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=True, default=None)
#     content = HTMLField('Content', null=True, default=None)
#     order = models.IntegerField(default=0)
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True , auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False , auto_now=True)
#
#     def __str__(self):
#         return "%s" % self.image
#
#     class Meta:
#         verbose_name = 'Пункт плана мероприятия'
#         verbose_name_plural = 'Пункты плана мероприятий'
#
#
# class EventResultPoint(models.Model):
#     title = models.CharField(max_length=64, blank=True, null=True, default=None)
#     event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=True, default=None)
#     content = HTMLField('Content', null=True, default=None)
#     order = models.IntegerField(default=0)
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True , auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False , auto_now=True)
#
#     def __str__(self):
#         return "%s" % self.image
#
#     class Meta:
#         verbose_name = 'Результат мероприятия'
#         verbose_name_plural = 'Результаты мероприятия'

from .signals import send_mail_join_event
post_save.connect(send_mail_join_event,sender=EventJoiner,dispatch_uid="my_unique_identifier")

events/forms.py
from django import forms
from .models import EventJoiner
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
# from django.forms import HiddenInput

class EventJoinForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = EventJoiner
        fields = ['customer_name', 'customer_email','customer_phone']

events/views.py
from django.shortcuts import render
from events.models import Event
from django.utils import timezone
from django.contrib.auth.models import User
from .forms import EventJoinForm
from .models import EventJoiner
from django.views import generic
from django.urls import reverse_lazy
from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404


def events_list(request):

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    print(request.session.session_key)

    events = Event.objects.filter(is_active=True, publicated__lte=timezone.now()).order_by('-event_date')
    events_live = Event.objects.filter(is_active=True, format__name='Очная', publicated__lte=timezone.now()).order_by('-event_date')
    events_online = Event.objects.filter(is_active=True, format__name='Онлайн', publicated__lte=timezone.now()).order_by('-event_date')

    return render(request, 'events/events.html', locals())



def event(request, pk):
    event = Event.objects.get(id=pk)

    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()
    return render(request, 'events/event.html', locals())


class EventJoinView(PassRequestMixin, SuccessMessageMixin, generic.CreateView):
	# model = EducationOrder
    template_name = 'events/event_join.html'
    form_class = EventJoinForm
    success_message = 'Ваша заявка принята, вскоре мы вам перезвоним.'
    # success_url = reverse_lazy('educations:education_n')
    def get_success_url(self):
        event_pk=self.kwargs['pk']
        return reverse_lazy('events:event_n', kwargs={'pk': event_pk})

    def form_valid(self, form):
        if 'referer' in self.request.session:
            referer_id = self.request.session['referer']
            user = User.objects.get(pk=referer_id)
            form.instance.referal = user.profile
        event = get_object_or_404(Event,pk=self.kwargs['pk'])
        form.instance.event = event
        return super(EventJoinView, self).form_valid(form)

templates/events/event.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}

<div class="container-fluid">
    <div class="row">
        <div class="card w-100 mb-3">
            <div class="card-header d-flex flex-column flex-md-row  justify-content-around p-1">
                <div class="col-md-5 mb-1">
                   <h4>{{ event.name }}</h4>
                   <div class="">
                       <span class="bg-warning p-1">{{ event.format }}</span>
                       {{ event.event_date }}
                   </div>
                </div>
                <div class="col-md-2 text-center order-md-3 px-0 py-1">
                    <div class="ya-share2" data-services="vkontakte,facebook,twitter,whatsapp,telegram"></div>
                    <h5 class="d-none d-md-block m-0">Поделиться</h5>
                </div>
                <button class="btn btn-dark btn-event col-md-3 flex-fill ml-auto p-3 p-md-2" type="button" data-id="{% url 'events:join_event_n' event.pk %}">
                    <h5 class="m-0">Записаться</h5>
                </button>
            </div>
            <div class="card-body">
       <!-- carousel start -->
                <div class="carousel-card no-border text-center w-100">
                    <div id="carousel-event" class="carousel slide carousel-fade" data-ride="carousel"  data-interval="999000" data-pause="False">
                        <div class="carousel-inner mw-50">
                            {% for image_item in event.eventimage_set.all %}
                            {% if image_item.is_main == True %}
                            <div class="carousel-item active">
                                {% else %}
                                <div class="carousel-item">
                                    {% endif %}
                                    <img class="d-block img-fluid mx-auto" src="{{ image_item.image.url }}" alt="">
                                </div>
                                {% endfor %}
                            </div>

                            <!-- carousel control  -->
                            <a class="carousel-control-prev" href="#carousel-event" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon bg-warning" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-event" role="button" data-slide="next">
                                <span class="carousel-control-next-icon bg-warning" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!-- carousel end -->
                        <div class="content">
                            {{ event.content | safe }}
                        </div>
                    </div>
                </div>
                <div class="card-footer p-1 text-right">
                   <small class="text-muted">
                       Опубликовано: {{ event.publicated }}
                   </small>
               </div>
               <button class="btn btn-dark btn-event col-md-5 p-3 p-md-2 d-md-none" type="button" data-id="{% url 'events:join_event_n' event.pk %}">
                   <h5 class="m-0">Записаться</h5>
               </button>
               <!-- <button class="btn btn-dark btn-lg btn-block btn-event" type="button" data-id="{% url 'events:join_event_n' event.pk %}"><span>Присоединиться к мероприятию</span></button> -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/events/event_join.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <p class="modal-title">Оставьте Ваши контакты и мы вам перезвоним!</p>
    <button type="button" class="close btn-dark" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
      <div class="form-row">
          <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
              {% for error in form.non_field_errors %}
              {{ error }}
              {% endfor %}
          </div>

          {% for field in form %}
          <div class="col-md-12">
              <label class="d-none invisible" for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% render_field field class="form-control my-1" placeholder=field.label %}
              <div class="{% if field.errors %} invalid{% endif %}">
                  {% for error in field.errors %}
                  <p class="help-block text-warning">{{ error }}</p>
                  {% endfor %}
              </div>
          </div>
          {% endfor %}
      </div>
  </div>

  <div class="modal-footer justify-content-center">
    <button type="button" class="submit-btn btn btn-dark">Заказать обучение!</button>
  </div>

</form>

templates/events/events.html
{% extends "wrapper.html" %}
{% block content %}
{% load static %}




<section class="container-fluid mb-5">
    <div class="row flex-column text-center">
        <h3 class="pt-5 pb-4 my-0">Мероприятия</h3>
        <ul class="nav nav-pills justify-content-center" id="pills-tab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="pills-events-clothest-tab" data-toggle="pill" href="#pills-events-clothest" role="tab" aria-controls="pills-events-clothest" aria-selected="true">Ближайшие</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-events-live-tab" data-toggle="pill" href="#pills-events-live" role="tab" aria-controls="pills-events-live" aria-selected="false">Очные</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="pills-events-online-tab" data-toggle="pill" href="#pills-events-online" role="tab" aria-controls="pills-events-online" aria-selected="false">Онлайн</a>
          </li>
        </ul>
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-events-clothest" role="tabpanel" aria-labelledby="pills-events-clothest-tab">
                {% for event_item in events %}
                {% include 'events/events_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-events-live" role="tabpanel" aria-labelledby="pills-events-live-tab">
                {% for event_item in events_live %}
                {% include 'events/events_cards.html' %}
                {% endfor %}
          </div>
          <div class="tab-pane fade" id="pills-events-online" role="tabpanel" aria-labelledby="pills-events-online-tab">
                {% for event_item in events_online %}
                {% include 'events/events_cards.html' %}
                {% endfor %}
          </div>
        </div>
    </div>
</section>


{% endblock content %}

templates/events/events_cards.html
{% load static %}
{% block events_cards %}

<section class="container-fluid">
    <div class="row justify-content-center pt-md-5">
        <div class="col-12 col-md-7 col-lg-8 col-xl-5 px-5 pt-5 pb-3 p-md-0 position-relative img-container">
            {% for image_item in event_item.eventimage_set.all %}
                {% if image_item.is_main == True %}
                <img class="img-fl" src="{{ image_item.image.url }}" alt="Card image cap">
                {% endif %}
            {% endfor %}
            <div class="in-event-date px-3 py-1">
                {{ event_item.event_date|date:'j F' }}
            </div>
        </div>
        <div class="col-12 col-md-5 col-lg-4 pb-0 px-5 py-md-5  text-left">
            <h3>{{ event_item.name }}</h3>
            <table class="py-1">
               <tr>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2  text-nowrap">{{ event_item.format }}</td>
                 <td><i class="fas fa-circle dot-size align-middle"></i></td>
                 <td class="px-2  text-nowrap">{{ event_item.event_date|date:'j F' }}</td>
               </tr>
            </table>
            <p class="py-3"> {{ event_item.description|truncatechars_html:500 }}</p>
            <a class="btn btn-outline-light btn-lg text-nowrap btn-pink" href="#" role="button">Записаться</a>
        </div>
    </div>
</section>

{% endblock events_cards %}